/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ajh5se (https://sketchfab.com/ajh5se)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/covid-proto-1-1a220d60ed1c4ccea867be647acc7f41
title: COVID Proto 1
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree, useFrame } from '@react-three/fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/COVID19_Draco.glb')
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    // state.camera.position.lerp(vec.set(0, 0, open ? -24 : -32), 0.1)
    // state.camera.lookAt(0, 0, 0)
    // group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, Math.cos(t / 2) / 8 + 0.25)
    // group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, Math.sin(t / 4) / 4)
    // group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, Math.sin(t / 4) / 4)
    // group.current.position.y = THREE.MathUtils.lerp(group.current.position.y, (-2 + Math.sin(t)) / 3)
    group.current.position.y = -20 + Math.sin(t) * 3
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Reflective282828} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Cartoon073FAA} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Cartoon930E1C} />
      </group>
    </group>
  )
}

useGLTF.preload('/COVID19_Draco.glb')
