/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/medical_Draco.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.05}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-44.28, -3.72, -130.86]} rotation={[0, -0.41, 0]}>
            <mesh
              geometry={nodes.PandemicSuit_Misc_Pandemic_Suit_0.geometry}
              material={nodes.PandemicSuit_Misc_Pandemic_Suit_0.material}
            />
            <mesh
              geometry={nodes.PandemicSuit_Misc_Pandemic_Suit_Misc_0.geometry}
              material={nodes.PandemicSuit_Misc_Pandemic_Suit_Misc_0.material}
            />
          </group>
          <group position={[0.01, -3.72, -0.34]}>
            <mesh
              geometry={nodes.PandemicSuit_Misc_2_Pandemic_Suit_0.geometry}
              material={nodes.PandemicSuit_Misc_2_Pandemic_Suit_0.material}
            />
            <mesh
              geometry={nodes.PandemicSuit_Misc_2_Pandemic_Suit_Misc_0.geometry}
              material={nodes.PandemicSuit_Misc_2_Pandemic_Suit_Misc_0.material}
            />
          </group>
          <group position={[35.19, -3.72, -62.99]}>
            <mesh
              geometry={nodes.PandemicSuit_Misc_3_Pandemic_Suit_0.geometry}
              material={nodes.PandemicSuit_Misc_3_Pandemic_Suit_0.material}
            />
            <mesh
              geometry={nodes.PandemicSuit_Misc_3_Pandemic_Suit_Misc_0.geometry}
              material={nodes.PandemicSuit_Misc_3_Pandemic_Suit_Misc_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/medical_Draco.gltf')
