/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: PatelDev (https://sketchfab.com/PatelDev)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/m18-smoke-grenade-a244dbffe2604d359f0295190fd2055c
title: M18 Smoke Grenade
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/smoke_grenade_Draco.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.11, 0.04, 0]} scale={0.81}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.004']} />
          </group>
          <group position={[0.12, 1.63, 0]} rotation={[0, 0, -Math.PI]} scale={[-0.03, 1.34, 0.23]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-0.73, 0.16, 0.88]} rotation={[Math.PI / 2, 0, 0]} scale={0.36}>
            <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
          </group>
          <group position={[-0.49, -0.19, 0.88]} rotation={[Math.PI / 2, 0, 0]} scale={0.36}>
            <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
          </group>
          <group position={[-0.83, -1.19, 0.58]} rotation={[Math.PI / 2, 0, 0]} scale={0.22}>
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
          </group>
          <group position={[-0.51, 0.47, 0.88]} rotation={[Math.PI / 2, 0, 0]} scale={0.36}>
            <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
          </group>
          <group position={[-0.02, 1.82, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.35, 0.29, 0.2]}>
            <mesh geometry={nodes.Object_18.geometry} material={materials['Material.005']} />
          </group>
          <group position={[-0.44, 2, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.06, 0.22, 0.06]}>
            <mesh geometry={nodes.Object_20.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-0.1, 1.5, 0]} scale={[0.46, 0.26, 0.46]}>
            <mesh geometry={nodes.Object_22.geometry} material={materials['Material.007']} />
          </group>
          <group position={[0.35, 1.81, 0.19]} rotation={[0, 0, -Math.PI / 2]} scale={[0.04, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
          </group>
          <group position={[0.3, 1.6, 0.37]} rotation={[0.96, -0.03, 0.02]} scale={[0.24, 0.17, 0.29]}>
            <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/smoke_grenade_Draco.gltf')
