/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/emoji_mobile_Draco.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[69, -42, 0]} rotation={[0, 1.17, 0]}>
        <group position={[0, 233.62, 6.81]}>
          <mesh
            geometry={nodes.Rectangle_2.geometry}
            material={nodes.Rectangle_2.material}
            position={[24.32, -0.8, 0.08]}
          />
          <mesh
            geometry={nodes.Rectangle_3.geometry}
            material={nodes.Rectangle_3.material}
            position={[-0.53, -0.8, 0.08]}
          />
          <mesh
            geometry={nodes.Rectangle_2_1.geometry}
            material={nodes.Rectangle_2_1.material}
            position={[0, -0.75, -0.02]}
          />
        </group>
        <group position={[-113.98, 110.12, -7.1]}>
          <mesh
            geometry={nodes.Rectangle_2_2.geometry}
            material={nodes.Rectangle_2_2.material}
            position={[237.84, -18.36, -0.5]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Rectangle_2_3.geometry}
            material={nodes.Rectangle_2_3.material}
            position={[10, -41.87, -0.5]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Rectangle_2_4.geometry}
            material={nodes.Rectangle_2_4.material}
            position={[10, 5.32, -0.5]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Rectangle_2_5.geometry}
            material={nodes.Rectangle_2_5.material}
            position={[10, 50.87, -0.5]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
        <mesh
          geometry={nodes.Brackets.geometry}
          material={nodes.Brackets.material}
          position={[120.62, -196.82, -5.52]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[-1, 1, 1]}
        />
        <mesh
          geometry={nodes.Brackets_1.geometry}
          material={nodes.Brackets_1.material}
          position={[-120.6, -196.82, -5.52]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Brackets_2.geometry}
          material={nodes.Brackets_2.material}
          position={[120.62, 201.5, -5.52]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[-1, 1, 1]}
        />
        <mesh
          geometry={nodes.Brackets_3.geometry}
          material={nodes.Brackets_3.material}
          position={[-120.6, 201.5, -5.52]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh geometry={nodes.Screen.geometry} material={nodes.Screen.material} position={[0, 0, 6.77]} />
        <mesh geometry={nodes.Rectangle.geometry} material={nodes.Rectangle.material} position={[0, 0, -13.31]} />
        <mesh geometry={nodes.Rectangle_1.geometry} material={nodes.Rectangle_1.material} position={[0, 0, -17.56]} />
      </group>
      <OrthographicCamera makeDefault={false} far={100000} near={-50000} position={[-2.56, 0, 999.86]}>
        <directionalLight
          intensity={0.75}
          decay={2}
          position={[850000, 1300000, 1000000]}
          rotation={[-0.92, 0.48, -0.34]}
        />
      </OrthographicCamera>
      <OrthographicCamera makeDefault={false} far={100000} near={-100000} position={[-10.38, -81.02, 999.86]} />
    </group>
  )
}

useGLTF.preload('/emoji_mobile_Draco.gltf')
