/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function IPhone({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/bCVt9EIOtmzt57DY/scene.splinecode')
  return (
      <group {...props} dispose={null}>
        <group name="object_mobile" position={[69, -42, 0]} rotation={[0, -0.01, 0]}>
          <mesh
            name="Brackets"
            geometry={nodes.Brackets.geometry}
            material={materials.blackparts}
            castShadow
            receiveShadow
            position={[120.62, -195.82, -5.52]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[-1, 1, 1]}
          />
          <mesh
            name="Brackets1"
            geometry={nodes.Brackets1.geometry}
            material={materials.blackparts}
            castShadow
            receiveShadow
            position={[-120.6, -195.82, -5.52]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Brackets2"
            geometry={nodes.Brackets2.geometry}
            material={materials.blackparts}
            castShadow
            receiveShadow
            position={[120.62, 202.5, -5.52]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[-1, 1, 1]}
          />
          <mesh
            name="Brackets3"
            geometry={nodes.Brackets3.geometry}
            material={materials.blackparts}
            castShadow
            receiveShadow
            position={[-120.6, 202.5, -5.52]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <group name="Notch" position={[0, 234.62, 21.14]}>
            <mesh
              name="Rectangle"
              geometry={nodes.Rectangle.geometry}
              material={materials.blackparts}
              castShadow
              receiveShadow
              position={[24.32, 233.82, 6.62]}
            />
            <mesh
              name="Rectangle1"
              geometry={nodes.Rectangle1.geometry}
              material={materials.blackparts}
              castShadow
              receiveShadow
              position={[-0.53, 233.82, 6.62]}
            />
            <mesh
              name="Rectangle 2"
              geometry={nodes['Rectangle 2'].geometry}
              material={materials.blackparts}
              castShadow
              receiveShadow
              position={[-10, 233.87, 20.85]}
            />
          </group>
          <mesh
            name="Screen"
            geometry={nodes.Screen.geometry}
            material={materials.screen}
            castShadow
            receiveShadow
            position={[0, 1, 22.33]}
          />
          <group name="Empty Object" position={[-113.98, 111.12, 8.46]}>
            <mesh
              name="Rectangle 21"
              geometry={nodes['Rectangle 21'].geometry}
              material={materials.blackparts}
              castShadow
              receiveShadow
              position={[123.86, 92.76, 7.96]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 22"
              geometry={nodes['Rectangle 22'].geometry}
              material={materials.blackparts}
              castShadow
              receiveShadow
              position={[-103.98, 69.25, 7.96]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 23"
              geometry={nodes['Rectangle 23'].geometry}
              material={materials.blackparts}
              castShadow
              receiveShadow
              position={[-103.98, 116.44, 7.96]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 24"
              geometry={nodes['Rectangle 24'].geometry}
              material={materials.blackparts}
              castShadow
              receiveShadow
              position={[-103.98, 161.98, 7.96]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
          <mesh
            name="Rectangle2"
            geometry={nodes.Rectangle2.geometry}
            material={materials.blackparts}
            castShadow
            receiveShadow
            position={[0, 1, 2.25]}
          />
          <mesh
            name="Rectangle3"
            geometry={nodes.Rectangle3.geometry}
            material={materials.back}
            castShadow
            receiveShadow
            position={[0, 1, -2]}
          />
        </group>
        <OrthographicCamera
          name="Default Camera"
          makeDefault={true}
          zoom={1.67}
          far={100000}
          near={-50000}
          position={[-2.56, 0, 999.86]}
        >
          <directionalLight
            name="SceneLightDirectionalDefault"
            intensity={0.75}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            position={[850000, 1300000, 1000000]}
          />
        </OrthographicCamera>
      </group>

  )
}
